# Generated by Django 4.2.5 on 2023-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='imagetype',
            field=models.CharField(choices=[('banner', 'Banner'), ('landscape', 'landscape'), ('specific', 'specific')], default='banner', max_length=50),
        ),
    ]
