# Generated by Django 4.2.5 on 2023-10-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_images_imagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='imagetype',
            field=models.CharField(choices=[('banner', 'Banner'), ('landscape', 'landscape'), ('specific', 'specific'), ('dp', 'dp')], default='banner', max_length=50),
        ),
    ]
